### ISSUE TITLE
Fix `NHENTAI_TAGS` Not Being Settable Via Docker Compose

### ISSUE THREAD

**Issue by 9-FS** [9-FS/nhentai_archivist#13]
Currently, `NHENTAI_TAGS` is not settable via docker compose, because docker compose does not seem to support array syntax for its environmental variables. All array entries must be made with 1 string. The usual solution seems to be to pass 1 string with comma separated values and split them manually in the program.

**Comment by 9-FS** [comment]
I've figured it out, and it doesn't even require a patch.

In your `docker-compose.yaml` you can use a similar syntax to the `./config/.env` file:

```YAML
environment:
    - NHENTAI_TAGS: '[language:"english"]' # all english hentai
    - NHENTAI_TAGS: '[tag:"big breasts"]' # all hentai with the tag "big breasts"
    - NHENTAI_TAGS: '[parody:"kono subarashii sekai ni syukufuku o"]' # all hentai from the anime "Kono Subarashii Sekai ni Syukufuku o"
    - NHENTAI_TAGS: '[artist:"shindol"]' # all hentai by Shindol
    - NHENTAI_TAGS: '[character:"frieren"]' # all hentai with character "Frieren"
    - NHENTAI_TAGS: '[tag:"ffm threesome", tag:"sister", -tag:"full censorship", -tag:"mind control"]' # all hentai with the tags "ffm threesome" and "sister" but without the tags "full censorship" and "mind control"
```

I'm adding this to the readme.
